//  Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: social-login
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2020-06-20
:page-essential: true
:page-essential-order: 1
:page-description: Learn how to authenticate users with the Open Liberty Social Media Login feature.
:guide-author: Open Liberty
:page-tags: ['Java EE', 'Jakarta EE', 'Security']
:page-related-guides: ['microprofile-jwt']
:page-permalink: /guides/{projectid}
:page-seo-title: Authenticating users with Social Media Login
:page-seo-description: A getting started tutorial with examples on how to secure Java applications by authenticating users through social media providers, such as GitHub, using the Open Liberty Social Media Login feature.
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
= Authenticating users through social media providers

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website^].

A getting started tutorial with examples on how to secure Java applications by authenticating users through social media providers, such as GitHub, using the Open Liberty Social Media Login feature.

== What you'll learn

Social Media Login provides a form of single sign-on (SSO) that enables users to sign in to a secured website by using
their existing social media account.
It simplifies the authentication process for end users and allows you to provide a secure authentication
method for your users without having to explicitly implement it.

The https://openliberty.io/docs/ref/feature/#socialLogin-1.0.html[Social Media Login Feature^] in Open Liberty
enables you to configure application authentication using one or more social media platforms,
including GitHub, LinkedIn, Facebook, Twitter and Google.
You can also create custom configuration for any other social media platform that implements
the https://oauth.net/2[OAuth 2.0^] or https://openid.net/connect[OpenID Connect 1.0^] standard for authorization.`

By the end of this guide, you will be able to authenticate users to your web service using GitHub.

// =================================================================================================
// Getting Started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]

== Creating a GitHub OAuth2 Application

Obtain an OAuth 2.0 client ID and client secret credentials for accessing the GitHub developer API by registering
a new https://github.com/settings/developers[application^] in your https://github.com/[GitHub^] account.
On the Settings > Developer settings > OAuth Apps page of your account, register a new application.

Set the Homepage URL to `\https://localhost:9443` and
the Authorization callback URL to `\https://localhost:9443/ibm/api/social-login/redirect/githubLogin`.

When the registration is complete, the client ID and client secret credentials are displayed.
To provide your application with the credentials, export the following environment variables: `GITHUB_CLIENT_ID` and
`GITHUB_CLIENT_SECRET`.

Replace the values of `[github-client-id]` and `[github-client-secret]` in the following command.
include::{common-includes}/os-tabs.adoc[]
[.tab_content.mac_section.linux_section]
--
[role='command']
----
export GITHUB_CLIENT_ID=[github-client-id]
export GITHUB_CLIENT_SECRET=[github-client-secret]
----
--
[.tab_content.windows_section]
--
[role='command']
----
set GITHUB_CLIENT_ID=[github-client-id]
set GITHUB_CLIENT_SECRET=[github-client-secret]
----
--

// =================================================================================================
// Building the application
// =================================================================================================
[role='command']
include::{common-includes}/devmode-build.adoc[]

== Configuring GitHub social media login
In the `start` directory, you are provided with an application that is secured through `BASIC` authentication.
When you access the `hello.html` page, you will find a `login` button.
When you click on the `login` button, a login dialog will open before redirecting you to the `/hello` endpoint served
by `HelloServlet`.

In this section, you will replace the login dialog with social media login through GitHub.

To enable login using social media providers for your application,
you need to add the `socialLogin-1.0` feature definition to the existing list of features.


