//  Copyright (c) 2017, 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: social-login
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2017-09-19
:page-essential: true
:page-essential-order: 1
:page-description: Learn how to secure a RESTful web service with the Open Liberty Social Media Login feature.
:guide-author: Open Liberty
:page-tags: ['Social Media Login', 'Java EE', 'Jakarta EE']
:page-related-guides: ['microprofile-jwt', 'security-intro', 'rest-client-java', 'rest-client-angularjs']
:page-permalink: /guides/{projectid}
:page-seo-title: Securing a RESTful web service with Social Media Login
:page-seo-description: A tutorial on how to secure a RESTful web service in Open Liberty using the SocialLogin feature
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
= Securing a RESTful web service with Social Media Login

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website^].

Learn how to secure a RESTful web service with the Open Liberty Social Media Login feature.

== What you'll learn

You will learn how to secure a simple RESTful web service using the https://openliberty.io/docs/ref/feature/#socialLogin-1.0.html[Social Media Login feature^]. You will secure an existing service,
`HelloService` using social media https://oauth.net/2[OAuth2^] and https://openid.net/connect[OpenID Connect^].

`HelloService` is a provided microservice that responds to a `GET` request with a Plain Text response that looks like this:

[source,role="no_copy"]
----
Hello, friend!
----

Instead of securing the `HelloService` service by implementing your own authentication service,
you can allow users to authenticate to the service using social media accounts.
This will allow you to provide a secure authentication method for your users without having to explicitly implement it.

Open Liberty provides a https://openliberty.io/docs/ref/feature/#socialLogin-1.0.html[Social Media Login feature^]
that provides configuration elements that allows you to use Facebook, Google, Github, Linkedin for authentication,
or to configure a custom OAuth2 or OpenID Connect provider.

By the end of this guide, you will secure the `HelloService` service with three social media login choices:

1. Github login
2. Amazon login
3. Google login

// =================================================================================================
// Getting Started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]

== Setting up the certificates and trust store

Before you can build the application, you will need to add the social media domains' certificates to the trust store for social media login.
The application you will build in this guide requires certificates for Amazon, Google and Github to be added to the trust store.
You also need to create certificates that your application will provide for HTTPS connections.
This certificate and private key will need to be added to the key store for social media login.
Lastly, you need to create an application on the three social media developer platforms to obtain a client ID and client secret to use their APIs.

First, navigate to the `start/src/main/liberty/config/resources/security` directory.

The instructions to get the certificates for Amazon, Google and Github depend on your OS and environment.
Use the following URLs when following the specific instructions for your OS to get the certificates for each service:

- Google: https://developers.google.com/[developers.google.com]
- Github: https://developer.github.com/[developer.github.com]
- Amazon: https://developer.amazon.com/[developer.amazon.com]

include::{common-includes}/os-tabs.adoc[]
[.tab_content.linux_section.mac_section]
--
You can use `openssl` to output the certificate chain for each URL and manually copy each certificate into a separate file.
To get the certificates using `openssl`:

Replace `<website URL>` with each URL mentioned above and run the following command in a terminal window:

[role='command']
----
openssl s_client \
    -showcerts \
    -connect <website URL>:443 </dev/null
----

In the command output, the contents of each certificate looks like:

[source,role="no_copy"]
----
-----BEGIN CERTIFICATE-----
fIIESjCCAzKgAwIBAgINAeO0mqGNiqmBJWlQuDANBgkqhkiG9w0BAQsFADBMMSAw
... more lines ...
-----END CERTIFICATE-----
----

Copy each certificate from the chain, including the `----BEGIN CERTIFICATE----` and `----END CERTIFICATE----`
and add it to a separate `.pem` file.
--

[.tab_content.windows_section]
--
Since there is no `openssl` command on Windows by default, the certificates can be retrieved from the URLs using an internet browser.
For example, to get the certificates using Firefox, perform the following steps for each
URL mentioned above:

1. Open the website on Firefox.
2. Click on the "Lock" icon to the left of the URL.
3. Click on the button next to "Connection Secure".
4. Click on "More Information".
5. Click on "View Certificate".

Clicking on "View Certificate" should open a new Firefox tab titled "Certificate".
Each certificate in the chain is in a separate tab in this page.
For each certificate in the chain, perform the following steps:

1. Navigate to the "Miscellaneous" section.
2. Click on "PEM (cert)" next to "Download" to download the certificate into a separate file.

For Firefox versions 70 and below, clicking on "View Certificate" should open a dialog box.

1. Switch to the "Details" tab.
2. For each certificate in the chain, click on the "Export..." button to export it as a separate `PEM` file.
--

Once you have the certificates downloaded, you need to add them to the trust store.
As part of the guide, you will configure the application's trust store to be `slts.p12` whose password is `changeit`.

To add a certificate to the trust store, substitute `<certificate-name>` with the name of the downloaded certificate
and `<certificate-alias>` with an alias you wish to give the certificate in the following command and run it.

include::{common-includes}/os-tabs.adoc[]
[.tab_content.linux_section.mac_section]
--
[role='command']
----
keytool \
    -import -trustcacerts \
    -file <certificate-name> \
    -alias <certificate-alias> \
    -keystore slts.p12 \
    -storetype PKCS12 \
    -storepass changeit
----
--

[.tab_content.windows_section]
--
[role='command']
----
keytool ^
    -import -trustcacerts ^
    -file <certificate-name> ^
    -alias <certificate-alias> ^
    -keystore slts.p12 ^
    -storetype PKCS12 ^
    -storepass changeit
----
--

The command also creates the trust store file if it doesn't exist.

Add each of the certificates that you downloaded to the `slts.p12` trust store.

include::{common-includes}/os-tabs.adoc[]
[.tab_content.linux_section.mac_section]
--
To generate certificates for your service to use for HTTPS connections, run the following command:
[role='command']
```
openssl req \
    -x509 \
    -newkey rsa:4096 \
    -keyout key.pem \
    -out cert.pem \
    -days 365 \
    -subj "/C=CA/CN=localhost"
```

Before the certificate and private key can be imported into the key store for your service, it needs to be converted into one `PKCS12` bundle.
Combine your key and certificate by running the following command. When prompted, set the password for the exported certificate bundle to `changeit`.
[role='command']
```
openssl pkcs12 \
    -inkey key.pem \
    -in cert.pem \
    -export -out certificate.p12
```

The key store to be used by social media login will be configured to be `key.p12` whose password is `changeit`.
To import your certificate bundle into this key store, run the following command:
[role='command']
```
keytool \
    -importkeystore \
    -srckeystore certificate.p12 \
    -srcstoretype PKCS12 \
    -destkeystore key.p12 \
    -deststoretype PKCS12
```
--

[.tab_content.windows_section]
--
To generate certificates for your service to use for HTTPS connections, run the following command:
[role='command']
```
powershell New-SelfSignedCertificate ^
    -Subject \"C=CA,CN=localhost\" ^
    -KeyAlgorithm RSA ^
    -KeyLength 4096 ^
    -CertStoreLocation "Cert:\CurrentUser\My" ^
    -FriendlyName "SocialLoginServer"
```

Before the certificate and private key can be imported into the key store for your service, it needs to be converted into one `PKCS12` bundle.
Export your newly created certificate by:

1. Search for "Manage user certificates" in the Start menu.
2. Epand "Personal".
3. Click on "Certificates".
4. Right-click the certificate entry with friendly name "SocialLoginServer".
5. Hover over "All tasks" in the dropdown menu to expand another dropdown menu.
6. Click "Export...". Then click "Next".
7. Select the radio button "Yes, export the private key".
8. Continue through the rest of the prompts in the Export wizard.
9. When prompted for a file name, click "Browse" to save the file in the current working directory.

The key store to be used by social media login will be configured to be `key.p12` whose password is `changeit`.
To import your certificate bundle into this key store, run the following command:
[role='command']
```
keytool `
    -importkeystore `
    -srckeystore certificate.pfx `
    -srcstoretype PKCS12 `
    -destkeystore key.p12 `
    -deststoretype PKCS12
```
--

The last prerequisite step is obtaining client ID and client secret for access to the three social media developer APIs.

In order to obtain OAuth 2.0 credentials for Google,
1. Visit the https://console.developers.google.com/[Google API Console].
2. Sign in using your Google account.
    1. If you haven't created a project on Google API Console before, you need to create one now before you can set up credentials.
    2. Once you have created the project, navigate to the "OAuth consent screen" tab. Click "External" and "Create". Fill in the "Application name".
3. Navigate to the "Credentials" tab. Click on the "Create Credentials" button. Select "OAuth Client ID" from the different options.
4. Set the application type to "Web Application" and fill the rest of the form.
5. Set the redirect URL to `\https://localhost:9443/ibm/api/social-login/redirect/googleOIDCLogin`.

In order to obtain OAuth 2.0 credentials for Amazon, follow the steps here: https://auth0.com/docs/connections/social/amazon.
Set the redirect URL to `\https://localhost:9443/ibm/api/social-login/redirect/amazonLogin`.

In order to obtain OAuth 2.0 credentials for Github, follow the steps here: https://auth0.com/docs/connections/social/github.
Set the redirect URL to `\https://localhost:9443/ibm/api/social-login/redirect/githubLogin`.

Enter the client IDs and client secrets to `src/main/liberty/config/server.xml` in the `start` folder.

== Securing HelloService

First, navigate to the `start` directory.
To start the Open Liberty server in development mode, run the `liberty:dev` goal in the `start` directory:

[role='command']
```
mvn liberty:dev
```

The [hotspot=helloService]`HelloService` class is the JAX-RS service that you will be securing.

[role="code_command", subs="quotes"] 
---- 
#Replace the `HelloService` class.#
`src/main/java/io/openliberty/guides/sociallogin/HelloService.java`
---- 

The following [hotspot=newImports]`new imports` are required for the `HelloService` class:

- [hotspot=rolesAllowedImport hotspot=rolesAllowed]`javax.annotation.security.RolesAllowed`
- [hotspot=httpServletRequestContextImport hotspot=httpServletRequestContext]`javax.servlet.http.HttpServletRequest`
- [hotspot=httpServletRequestContextImport hotspot=httpServletRequestContext]`javax.ws.rs.core.Context`

The [hotspot=rolesAllowed]`@RolesAllowed({"users"})` annotation restricts access to the service to users who are
in the `users` role.

The `return "Hello, friend!";` is replaced to [hotspot=userPrincipal]`output user information`.
The [hotspot=httpServletRequestContext]`HttpServletRequest` context, which is injected using the
[hotspot=contextAnnotation]`@Context` annotation, allows you to get information about the logged in user
using [hotspot=userPrincipal]`request.getUserPrincipal()`.

HelloService.java 
[source, Java, linenums, role='code_column hide_tags=copyright'] 
----
include::finish/src/main/java/io/openliberty/guides/sociallogin/HelloService.java[]
----

== Configuring the security and social media login

[role="code_command", subs="quotes"] 
---- 
#Replace the server configuration file.#
`src/main/liberty/config/server.xml`
----

server.xml 
[source, xml, linenums, role='code_column']
---- 
include::finish/src/main/liberty/config/server.xml[]
---- 

The explanation for these changes are in the following sections.

=== Configuring the security roles

The [hotspot=applicationBnd]`<application-bnd />` configuration element under the
[hotspot=webApplication]`<webApplication />` configuration element creates a new security role `users`,
which all authenticated users belong to.
Adding this allows users that are authenticated using social media login to access your `HelloService` service.

server.xml
[source, xml, linenums, role='code_column']
----
include::finish/src/main/liberty/config/server.xml[]
---- 

=== Adding required features

To enable https://openliberty.io/docs/ref/feature/#socialLogin-1.0.html[Social Media Login feature^] and other required features, add new [hotspot=newFeatures]`<feature />` elements to the [hotspot=featureManager]`<featureManager />` in
`src/main/liberty/config/server.xml`

There are some prerequisite configurations that social media login configuration elements need:

1. A [hotspot=keystore]`<keyStore />` configuration element that corresponds to the key store created in the prerequisites section
2. A [hotspot=truststore]`<keyStore />` configuration element that corresponds to the trust store created in the prerequisites section
3. An [hotspot=sslConfig]`<ssl />` configuration element for configuring the SSL configuration that is used to connect to the social media

=== Adding key store and trust store

In the first section, you created two key stores, `slts.p12` and `key.p12`.
Now you will configure your application to use these key stores.
Files in the `src/liberty` folder are copied into the location specified by `${server.output.dir}`,
so the location of these key stores is `${server.output.dir}/resources/security`.

The [hotspot=keystore]`defaultKeyStore` configuration element whose location is `${server.output.dir}/resources/security/key.p12`
will be used to provide SSL certificates when initiating HTTPS connections for social media login.
Provide the password that you used when creating the key store.

The [hotspot=truststore]`socialLoginKeyStore` configuration element whose locaiton is `${server.output.dir}/resources/security/slts.p12`
will be used to store trusted certificates when initiating HTTPS connections to social media APIs for authorization and authentication.
Provide the password that you usd when creating the trust store.

The [hotspot=sslConfig]`authServiceSslRef` configuration element which references [hotspot=keystore]`defaultKeyStore` as the key store
and [hotspot=truststore]`socialLoginKeyStore` as the trust store will be provided to social media login configurations.

=== Adding Github login configuration

The [hotspot=githubLogin]`<githubLogin />` configuration element will configure Github login.
Replace the values of the [hotspot=43]`clientId` and [hotspot=44]`clientSecret` with the credentials you created for your Github application
in the prerequisites section. The [hotspot=45]`sslRef` attribute is set to the [hotspot=sslConfig]`authServiceSslRef` configuration from the previous section.

=== Adding Amazon login configuration

The [hotspot=amazonLogin]`amazonLogin` configuration uses a custom `<oauth2Login />` configuration element.
Replace the values of [hotspot=52]`clientId` and [hotspot=53]`clientSecret` with the credentials you created for your Amazon application
in the prerequisites section. The [hotspot=55]`sslRef` attribute is set to the [hotspot=sslConfig]`authServiceSslRef` configuration from the previous section.
The following attributes are set for your [hotspot=amazonLogin]`<oauth2Login />` configuration element:

- [hotspot=54]`responseType`: `code`
- [hotspot=56]`tokenEndpointAuthMethod`: `client_secret_post`
- [hotspot=57]`authorizationEndpoint`: `\https://www.amazon.com/ap/oa`
- [hotspot=58]`tokenEndpoint`: `\https://api.amazon.com/auth/o2/token`
- [hotspot=60]`scope`: `profile`
- [hotspot=59]`userApi`: `\https://api.amazon.com/user/profile`
- [hotspot=61]`userNameAttribute`: `name`
- [hotspot=62]`userUniqueIdAttribute`: `user_id`
- [hotspot=63]`website`: `www.amazon.com`
- [hotspot=51]`displayName`: `Amazon`

Further documentation on these attributes can be found on the https://openliberty.io/docs/ref/config/oauth2Login.html[Open Liberty config reference on oauth2Login^].
The values for these attributes can be found in the https://developer.amazon.com/docs/login-with-amazon/minitoc-lwa-overview.html[Login With Amazon API documentation^].

Make sure that the [hotspot=50]`id` of your [hotspot=amazonLogin]`<oauth2Login />` configuration matches the redirect URL (if you set the [hotspot=50]`id` to `amazonLogin`, the redirect URL must end with `.../amazonLogin`).

=== Adding Google login configuration

The [hotspot=googleOIDCLogin]`googleOIDCLogin` configuration uses a custom `<oidcLogin />` configuration element.
Repalce the values of [hotspot=70]`clientId` and [hotspot=71]`clientSecret` with the credentials you created for your Google application
in the prerequisites section. The [hotspot=72]`sslRef` attribute is set to the [hotspot=sslConfig]`authServiceSslRef` configuration from the previous section.
The following attributes are set for your [hotspot=googleOIDCLogin]`<oidcLogin />` configuration element:

- [hotspot=69]`displayName`: `Google`
- [hotspot=73]`authorizationEndpoint`: `\https://accounts.google.com/o/oauth2/v2/auth`
- [hotspot=74]`tokenEndpoint`: `\https://www.googleapis.com/oauth2/v4/token`
- [hotspot=75]`jwksUri`: `\https://www.googleapis.com/oauth2/v3/certs`
- [hotspot=76]`scope`: `openid profile email`
- [hotspot=77]`userNameAttribute`: `email`
- [hotspot=78]`realmNameAttribute`: `iss`
- [hotspot=79]`issuer`: `\https://accounts.google.com`

Further documentation on these attributes can be found on the https://openliberty.io/docs/ref/config/oidcLogin.html[Open Liberty config reference on oidcLogin^].
The values of these attributes can be found in the https://developers.google.com/identity/protocols/OpenIDConnect[Google API documentation^].

Make sure that the [hotspot=68]`id` of your [hotspot=googleOIDCLogin]`<oidcLogin />` configuration matches the redirect URL (if you set the [hotspot=68]`id` to `googleOIDCLogin`, the redirect URL must end with `.../googleOIDCLogin`).

== Building and running the application

The Open Liberty server was started in development mode at the beginning of the guide and all the 
changes were automatically picked up.

Check out the service that you created at the
http://localhost:9080/api/hello[^] URL.

When the server updates its configuration, when you access https://localhost:9080/api/hello[the endpoint for Hello service^],
you should be redirected to a Social Media Login Form. This form allows you to choose which login provider you want to use
for authentication. When you select a login choice, you will be redirected to the login page of that service.

Try logging in using your social media accounts. After authenticating, you will be redirected back to https://localhost:9080/api/hello and the response will look like this:

[source,role="no_copy"]
----
Hello, <<your username>>
WSPrincipal:<<your username>>
----

== Testing the service

No automated tests are provided in this guide.
You can test this service manually by starting a server and pointing a web browser at http://localhost:9080/api/hello[the endpoint for Hello service^].

== Great work! You're done!

You secured a simple RESTful web service in Open Liberty by using the Social Media Login feature.

== Related Links

Learn more about MicroProfile.

https://microprofile.io/[See the MicroProfile specs^]

https://openliberty.io/docs/ref/microprofile[View the MicroProfile API^]


include::{common-includes}/attribution.adoc[subs="attributes"]
