//  Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: social-login
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2020-06-20
:page-essential: true
:page-essential-order: 1
:page-description: Learn how to authenticate users with the Open Liberty Social Media Login feature.
:guide-author: Open Liberty
:page-tags: ['Java EE', 'Jakarta EE', 'Security']
:page-related-guides: ['microprofile-jwt']
:page-permalink: /guides/{projectid}
:page-seo-title: Authenticating users with Social Media Login
:page-seo-description: A getting started tutorial with examples on how to secure Java applications by authenticating users through social media providers, such as GitHub, using the Open Liberty Social Media Login feature.
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
= Authenticating users through social media providers

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website^].

A getting started tutorial with examples on how to secure Java applications by authenticating users through social media providers, such as GitHub, using the Open Liberty Social Media Login feature.

== What you'll learn

Social Media Login provides a form of single sign-on (SSO) that enables users to sign in to a secured website by using
their existing social media account.
It simplifies the authentication process for end users and allows you to provide a secure authentication
method for your users without having to explicitly implement it.

The https://openliberty.io/docs/ref/feature/#socialLogin-1.0.html[Social Media Login Feature^] in Open Liberty
enables you to configure application authentication using one or more social media platforms,
including GitHub, LinkedIn, Facebook, Twitter and Google.
You can also create custom configuration for any other social media platform that implements
the https://oauth.net/2[OAuth 2.0^] or https://openid.net/connect[OpenID Connect 1.0^] standard for authorization.`

By the end of this guide, you will be able to authenticate users to your web service using GitHub.

// =================================================================================================
// Getting Started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]

== Creating a GitHub OAuth2 Application

Obtain an OAuth 2.0 client ID and client secret credentials for accessing the GitHub developer API by registering
a new https://github.com/settings/developers[application^] in your https://github.com/[GitHub^] account.
On the Settings > Developer settings > OAuth Apps page of your account, register a new application.

Set the Homepage URL to `\https://localhost:9443` and
the Authorization callback URL to `\https://localhost:9443/ibm/api/social-login/redirect/githubLogin`.

When the registration is complete, the client ID and client secret credentials are displayed.
To provide your application with the credentials, export the following environment variables: `GITHUB_CLIENT_ID` and
`GITHUB_CLIENT_SECRET`.

Replace the values of `[github-client-id]` and `[github-client-secret]` in the following command.
include::{common-includes}/os-tabs.adoc[]
[.tab_content.mac_section.linux_section]
--
[role='command']
----
export GITHUB_CLIENT_ID=[github-client-id]
export GITHUB_CLIENT_SECRET=[github-client-secret]
----
--
[.tab_content.windows_section]
--
[role='command']
----
set GITHUB_CLIENT_ID=[github-client-id]
set GITHUB_CLIENT_SECRET=[github-client-secret]
----
--

== Configuring GitHub social media login
In the `start` directory, you are provided with an application that is secured through `BASIC` authentication.
When you access the [hotspot file=1]`hello.html` page, you will find a [hotspot=btnLogin file=1]`login` button.

When you click on the [hotspot=btnLogin file=1]`login` button, a login dialog will open before redirecting you to the
[hotspot=login file=1]`/hello` endpoint served by [hotspot file=2]`HelloServlet`, which serves the
[hotspot=serve file=2]`securedHello.jsp` page.

The [hotspot file=3]`securedHello.jsp` page contains a [hotspot=btnLogout file=3]`logout` button that makes a
`POST` request to the [hotspot=logout file=3]`/logout` endpoint served by [hotspot file=4]`LogoutServlet`.

Enabling the Social Login feature will replace the login dialogue with social media login.

[role="code_command", subs="quotes"]
----
#Update this `server.xml` file.#
`src/main/liberty/config/server.xml`
----
[role="edit_command_text"]
Add the [hotspot=socialLogin file=0]`socialLogin-1.0` feature definition to the existing list of features.
Add the [hotspot=githubLogin file=0]`<githubLogin />` configuration element to the server configuration.

Adding the [hotspot=socialLogin file=0]`socialLogin-1.0` feature definition enables social media login functionality to
the application.
This allows us to use the [hotspot=githubLogin file=0]`<githubLogin />` configuration element to configure GitHub login.

The client ID and client secret for your GitHub OAuth2 application are injected into the
[hotspot=githubLogin file=0]`<githubLogin />` configuration element with the values of `github.client.id` and
`github.client.secret`.
These values are supplied using the environment variables `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET`.

server.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/liberty/config/server.xml[]
----

hello.html
[source ,html, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/webapp/hello.html[]
----

HelloServlet.java
[source ,java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/sociallogin/HelloServlet.java[]
----

securedHello.jsp
[source ,html, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/webapp/securedHello.jsp[]
----

LogoutServlet.java
[source ,java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/sociallogin/LogoutServlet.java[]
----

// =================================================================================================
// Building the application
// ================================================================================================
[role='command']
include::{common-includes}/devmode-build.adoc[]

Check out the service that you created at the
http://localhost:9080/api/hello.html[^] URL.

Try logging in using your social media account.
After authenticating, you will be redirected to `\https://localhost:9080/api/hello`.
When you click the `logout` button, you will be unauthenticated and redirected back to
http://localhost:9080/api/hello.html[^].

== Implementing logout

The [hotspot file=2]`LogoutServlet` provided in the `start` directory uses the
[hotspot=logout file=2]`HttpServletRequest#logout()`
method to log the user out of the application, after which the user is redirected to
[hotspot=redirect file=2]`hello.html`.

You are also provided with a [hotspot file=1]`LogoutHandler` class and [hotspot file=3]`ILogout` interface to add
custom logout logic to revoke the application's permissions from a user's account when they choose to log out of the
application.
In this section, you will implement `ILogout` for revoking permissions for the application from the
user's GitHub account.

[role="code_command", subs="quotes"]
----
#Create this `GitHubLogout` class.#
`src/main/java/io/openliberty/guides/sociallogin/logout/GitHubLogout.java`
----

A `DELETE` request to the [hotspot=unauthorizeUrl file=0]`unauthorizeUrl` is performed using
the JAX-RS [hotspot=delete file=0]`ClientBuilder` to revoke permissions.

The [hotspot=encodeAuth file=0]`encoded` client ID and client secret, obtained from the `github.client.id` and
`github.client.secret` config properties are added to the request as an
[hotspot=authHeader file=0]`Authorization: Basic ...` header.

The GitHub [hotspot=accessToken file=0]`access token` retrieved from the user's `UserProfile` using the
[hotspot=accessToken file=0]`UserProfileManager`, is sent as part of the
[hotspot=requestBody hotspot=accessTokenBody file=0]`request body`.

[role="code_command", subs="quotes"]
----
#Update this `LogoutHandler` class.#
`src/main/java/io/openliberty/guides/sociallogin/logout/LogoutHandler.java`
----
[role="edit_command_text"]
Inject [hotspot=inject file=1]`GitHubLogout`.
Add a switch case for [hotspot=handleGithubLogout file=1]`githubLogin` which returns an instance of `GitHubLogout`.

`LogoutHandler` will [hotspot=switch file=1]`return` the implementation of `ILogout` based on the name of the social
media provider used by a user which is retrieved using the [hotspot=socialMediaName file=1]`UserProfileManager`.
The social media name returned by [hotspot=socialMediaName file=1]`UserProfileManager` is the `id` of the login
configuration.

In this case, when the user uses GitHub, the name of the social media provider is
[hotspot=githubLoginName file=1]`githubLogin`.

[role="code_command", subs="quotes"]
----
#Update this `LogoutServlet` class.#
`src/main/java/io/openliberty/guides/sociallogin/LogoutServlet.java`
----
[role="edit_command_text"]
Inject [hotspot=inject file=2]`LogoutHandler`.
Add [hotspot=revoke file=2]`logoutHandler.getLogout().logout()` to revoke
application permissions.
Add [hotspot=errorHandle file=2]`error handling` when the response returned by
[hotspot=revoke file=2]`logoutHandler.getLogout().logout()` is not `2xx`.

Before using [hotspot=logout file=2]`HttpServletRequest#logout()`
to log the user out of the application, [hotspot=revoke file=2]`LogoutHandler#getLogout()` gets `GitHubLogout` and
revokes OAuth2 permissions granted to the application by the user using [hotspot=revoke file=2]`GitHubLogout#logout()`.

GitHubLogout.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/sociallogin/logout/GitHubLogout.java[]
----

LogoutHandler.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/sociallogin/logout/LogoutHandler.java[]
----

LogoutServlet.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/sociallogin/LogoutServlet.java[]
----

ILogout.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/sociallogin/logout/ILogout.java[]
----

// =================================================================================================
// Building the application
// ================================================================================================
[role='command']
include::{common-includes}/devmode-build.adoc[]

Check out the service that you created at the
http://localhost:9080/api/hello.html[^] URL.

Try logging in using your social media account.
After authenticating, you will be redirected to `\https://localhost:9080/api/hello`.
When you click the `logout` button, you will be unauthenticated and redirected back to
http://localhost:9080/api/hello.html[^].

If you try logging in again, you will be asked to reauthorize your application with GitHub before being authenticated and
redirected to `\https://localhost:9080/api/hello`.

[role='command']
include::{common-includes}/devmode-quit.adoc[]

== Great work! You're done!

You secured a simple RESTful web service in Open Liberty by using the Social Media Login feature.

== Next Steps

As an exercise, configure a second social media provider, Facebook, for social media login for your application.
If more than one social media login provider is added, there’s a selection form presented to the user,
where all the possible social media providers configured in your application are shown for the user to pick from.

You can create the `<facebookLogin />` configuration element in `server.xml` to setup login for Facebook.
Similar to `<githubLogin />`, `<facebookLogin />` also only requires a client ID and client secret.
The following links to Facebook documentation will provide any additional information about setting up an OAuth2
application.

- https://developers.facebook.com/docs/apps#register[Registering for a Facebook application^]
- https://developers.facebook.com/docs/facebook-login/web#redirecturl[Adding Facebook Login to your Facebook Application^]
- https://developers.facebook.com/docs/facebook-login/permissions/requesting-and-revoking#revokelogin[Revoking Facebook Login^]

== Related Links

Learn more about MicroProfile.

https://microprofile.io/[See the MicroProfile specs^]

https://openliberty.io/docs/ref/microprofile[View the MicroProfile API^]


include::{common-includes}/attribution.adoc[subs="attributes"]
