//  Copyright (c) 2017, 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: social-login
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2017-09-19
:page-essential: true
:page-essential-order: 1
:page-description: Learn how to authenticate users with the Open Liberty Social Media Login feature.
:guide-author: Open Liberty
:page-tags: ['Java EE', 'Jakarta EE', 'Security']
:page-related-guides: ['microprofile-jwt', 'security-intro', 'rest-client-java', 'rest-client-angularjs']
:page-permalink: /guides/{projectid}
:page-seo-title: Authenticating users with Social Login
:page-seo-description: A tutorial on how to authenticate users in Open Liberty using the Social Media Login feature
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
= Authenticating users with Social Login

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website^].

Learn how to authenticate users with the Open Liberty Social Media Login feature.

== What you'll learn

You will learn how to authenticate users to an existing service using Social Media Login.

Social Media Login provides a form of single sign-on (SSO) that enables users to sign in to a secured website by using
their existing social media account.
It simplifies the authentication process for end users and allows you to provide a secure authentication
method for your users without having to explicitly implement it.

The https://openliberty.io/docs/ref/feature/#socialLogin-1.0.html[Social Media Login Feature^] in Open Liberty
enables you to configure application authentication using one or more social media platforms,
including GitHub, LinkedIn, Facebook, Twitter and Google.
You can also create custom configuration for any other social media platform that implements
the https://oauth.net/2[OAuth 2.0^] or https://openid.net/connect[OpenID Connect 1.0^] standard for authorization.`

By the end of this guide, you will be able to authenticate users to your web service using GitHub.

// =================================================================================================
// Getting Started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]

== Creating a GitHub OAuth2 Application

To obtain OAuth 2.0 client ID and client secret credentials for accessing the GitHub developer API,

. Log into https://github.com/[GitHub^].
. Navigate to https://github.com/settings/developers[OAuth Apps^] and click on "Register a new application".
. Enter an application name.
. Set "Homepage URL" to `\https://localhost:9443/`.
. Set "Authorization callback URL" to `\https://localhost:9443/ibm/api/social-login/redirect/githubLogin`.
. Click on "Register application".

== Securing HelloService

First, navigate to the `start` directory.

[role='command']
include::{common-includes}/devmode-start.adoc[]

The [hotspot=helloService]`HelloService` class is the JAX-RS service that you will be securing.
`HelloService` responds to a `GET` request with the following Plain Text response:

[source,role="no_copy"]
----
Hello, friend!
----

[role="code_command hotspot file=0", subs="quotes"] 
----
#Replace the `HelloService` class.#
`src/main/java/io/openliberty/guides/sociallogin/HelloService.java`
----

The following new imports are required for the [hotspot=helloService]`HelloService` class:

- [hotspot=rolesAllowedImport]`javax.annotation.security.RolesAllowed`
- [hotspot=securityContextImport]`javax.ws.rs.core.SecurityContext`
- [hotspot=contextImport]`javax.ws.rs.core.Context`

The [hotspot=rolesAllowed]`@RolesAllowed({"users"})` annotation restricts access to the service to users who are
in the `users` role.

The `return "Hello, friend!";` is replaced to output user information.
The [hotspot=securityContext]`SecurityContext` context, which is injected using the
[hotspot=securityContext]`@Context` annotation, allows you to get information about the logged-in user
using [hotspot=userPrincipal]`securityContext.getUserPrincipal()`.

HelloService.java 
[source, Java, linenums, role='code_column hide_tags=copyright'] 
----
include::finish/src/main/java/io/openliberty/guides/sociallogin/HelloService.java[]
----

== Configuring the security and social media login

[role="code_command hotspot file=0", subs="quotes"] 
----
#Replace the server configuration file.#
`src/main/liberty/config/server.xml`
----

server.xml 
[source, xml, linenums, role='code_column']
----
include::finish/src/main/liberty/config/server.xml[]
----

The explanations for these changes are in the following sections.

=== Configuring the security roles

The [hotspot=applicationBnd]`<application-bnd />` configuration element under the
[hotspot=webApplication]`<webApplication />` configuration element creates a new security role [hotspot=users]`users`,
which all authenticated users belong to.
Adding this allows users that are authenticated using social media login to access your `HelloService` service.

=== Adding required features

To enable https://openliberty.io/docs/ref/feature/#socialLogin-1.0.html[Social Media Login feature^] and other required features,
new [hotspot=newFeatures]`<feature />` elements are added to the [hotspot=featureManager]`<featureManager />` in
`server.xml`.

There are some prerequisite configurations that social media login configuration elements need:

1. The [hotspot=keystore]`<keyStore id="defaultKeyStore" .../>` configuration element
corresponds to the keystore created in the prerequisites section
2. An [hotspot=sslConfig]`<ssl id="authServiceSslRef .../>` configuration element for configuring the SSL configuration that is used to connect to the social media

=== Adding keystore and truststore

The [hotspot=keystore]`<keyStore id="defaultKeyStore" .../>` configuration element
will be used to provide SSL certificates when initiating HTTPS connections for social media login.

[role="code_command hotspot=sections", subs="quotes"] 
----
#Update the `server.xml` file.#
`src/liberty/config/server.xml`
----
[role="edit_command_text"]
Replace [hotspot=22]`[keystore-password]` with the password that you used when creating the keystore in the previous sections.

The [hotspot=sslConfig]`<ssl id="authServiceSslRef" .../>` configuration element, which references [hotspot=keystore]`<keyStore id="defaultKeyStore" .../>` as the keystore, will be provided to social media login configurations.

For your application to send data securely to the social media platforms, it must trust the public SSL certificates
provided by them.
This requires the SSL certificates for Amazon, Google and GitHub to be added to a truststore.

Since the platforms in this guide use a well-known CA (Certificate Authority), they can be
found in the JDK default `cacerts` file.

The [hotspot=30]`trustDefaultCerts` attribute of the [hotspot=sslConfig]`<ssl id="authServiceSslRef" .../>` configuration element,
when set to true, allows the server to establish trust using the JDK default truststore, instead of requiring
you to create a truststore with the required certificates.

=== Adding GitHub login configuration

[role="code_command hotspot=sections", subs="quotes"] 
----
#Update the `server.xml` file.#
`src/liberty/config/server.xml`
----
[role="edit_command_text"]
Replace the values of the [hotspot=36]`clientId` and [hotspot=37]`clientSecret` with the credentials you created for your GitHub application
in the prerequisites section.

The [hotspot=githubLogin]`<githubLogin />` configuration element will configure GitHub login.
The [hotspot=38]`sslRef` attribute is set to the [hotspot=sslConfig]`authServiceSslRef` configuration from the previous section.

== Running the application

The Open Liberty server was started in development mode at the beginning of the guide and all the 
changes were automatically picked up.

Check out the service that you created at the
http://localhost:9080/api/hello[^] URL.

Try logging in using your social media account.
After authenticating, you will be redirected back to https://localhost:9080/api/hello and the response will look like this:

[source,role="no_copy"]
----
Hello, <<your username>>
----

== Testing the service

No automated tests are provided in this guide.
You can test this service manually by starting a server and pointing a web browser at http://localhost:9080/api/hello[the endpoint for Hello service^].

== Great work! You're done!

You secured a simple RESTful web service in Open Liberty by using the Social Media Login feature.

== Related Links

Learn more about MicroProfile.

https://microprofile.io/[See the MicroProfile specs^]

https://openliberty.io/docs/ref/microprofile[View the MicroProfile API^]


include::{common-includes}/attribution.adoc[subs="attributes"]
