//  Copyright (c) 2017, 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: social-login
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2017-09-19
:page-essential: true
:page-essential-order: 1
:page-description: Learn how to secure a RESTful web service with the Open Liberty Social Media Login feature.
:guide-author: Open Liberty
:page-tags: ['Java EE', 'Jakarta EE', 'Security']
:page-related-guides: ['microprofile-jwt', 'security-intro', 'rest-client-java', 'rest-client-angularjs']
:page-permalink: /guides/{projectid}
:page-seo-title: Securing a RESTful web service with Social Media Login
:page-seo-description: A tutorial on how to secure a RESTful web service in Open Liberty using the Social Media Login feature
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
= Securing a RESTful web service with Social Media Login

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website^].

Learn how to secure a RESTful web service with the Open Liberty Social Media Login feature.

== What you'll learn

You will learn how to secure a simple RESTful web service using the https://openliberty.io/docs/ref/feature/#socialLogin-1.0.html[Social Media Login feature^]. You will secure an existing service,
`HelloService`, using social media https://oauth.net/2[OAuth2^] and https://openid.net/connect[OpenID Connect^].

`HelloService` is a provided microservice that responds to a `GET` request with the following Plain Text response:

[source,role="no_copy"]
----
Hello, friend!
----

Instead of securing the `HelloService` service by implementing your own authentication service,
you can allow users to authenticate the service using social media accounts.
This will allow you to provide a secure authentication method for your users without having to explicitly implement it.

Open Liberty provides a https://openliberty.io/docs/ref/feature/#socialLogin-1.0.html[Social Media Login Feature^]
that provides configuration elements that allow you to configure an OAuth2 or OpenID Connect provider.
The feature also provides preconfigured elements for common social media platforms like Facebook, Google, GitHub, LinkedIn and Twitter,
which only require that you provide the credentials obtained by registering for an application on that platform.

By the end of this guide, you will be able to secure the HelloService service using:

1. A pre-configured social media login (GitHub)
2. A custom OAuth2 login provider configuration (Amazon)
3. A custom OIDC login provider configuration (Google)

// =================================================================================================
// Getting Started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]

== Setting up the certificates and truststore

The application you will build in this guide requires certificates for Amazon, Google and GitHub to be added to the truststore.
You also need to create a server certificate that your application will provide for HTTPS connections, and corresponding private key to decrypt the incoming secure data.
This certificate and private key will need to be added to the keystore for social media login.
Lastly, you need to create an application on the three social media developer platforms to obtain a client ID and client secret to use their APIs.

First, navigate to the `start/src/main/liberty/config/resources/security` directory.

=== Generating a self signed certificate
Your application requires a TLS server certificate and corresponding private key to securely communicate using HTTPS. In this section, you will
generate a self signed certificate and add it to your `key.p12`, which you will be your application's keystore.

To create a self-signed certificate and add it to `key.p12` using the Java `keytool`,
run the following command. Replace `[keystore-password]` with a password for your keystore.
You will need this password in later sections in the guide.
include::{common-includes}/os-tabs.adoc[]
[.tab_content.linux_section.mac_section]
--
[role='command']
```
keytool -genkey \
    -keyalg RSA \
    -alias selfsigned \
    -keystore key.p12 \
    -storetype PKCS12
    -storepass [keystore-password] \
    -validity 360 \
    -keysize 2048
```
--
[.tab_content.windows_section]
--
[role='command']
```
%JAVA_HOME%\bin\keytool -genkey ^
    -keyalg RSA ^
    -alias selfsigned ^
    -keystore key.p12 ^
    -storetype PKCS12 ^
    -storepass [keystore-password] ^
    -validity 360 ^
    -keysize 2048
```
--

=== Setting up for GitHub
For your application to communicate securely with GitHub using HTTPS, the TLS server public key certificates for the following domains need to be added to your application's truststore:

- `www.github.com` (will be saved as `github.pem`)
- `api.github.com` (will be saved as `github_api.pem`)

To download the certificates, run the following commands:

include::{common-includes}/os-tabs.adoc[]
[.tab_content.linux_section.mac_section]
--
[role='command']
```
keytool \
    -printcert -rfc \
    -sslserver www.github.com:443 \
    > github.pem
keytool \
    -printcert -rfc \
    -sslserver api.github.com:443 \
    > github_api.pem
```
--
[.tab_content.windows_section]
--
[role='command']
```
%JAVA_HOME%\bin\keytool ^
    -printcert -rfc ^
    -sslserver www.github.com:443 ^
    > github.pem
%JAVA_HOME%\bin\keytool ^
    -printcert -rfc ^
    -sslserver api.github.com:443 ^
    > github_api.pem
```
--

Next, run the following command to add the downloaded certificates into a keystore named `slts.p12`, which will be your application's truststore. Replace `[truststore-password]` with a password for your truststore.
You will need this password in later sections in the guide.

include::{common-includes}/os-tabs.adoc[]
[.tab_content.linux_section.mac_section]
--
[role='command']
```
keytool \
    -import -trustcacerts \
    -file github.pem \
    -alias github \
    -keystore slts.p12 \
    -storetype PKCS12 \
    -storepass [truststore-password] \
    -noprompt
keytool \
    -import -trustcacerts \
    -file github_api.pem \
    -alias github_api \
    -keystore slts.p12 \
    -storetype PKCS12 \
    -storepass [truststore-password] \
    -noprompt
```
--
[.tab_content.windows_section]
--
[role='command']
```
%JAVA_HOME%\bin\keytool ^
    -import -trustcacerts ^
    -file github.pem ^
    -alias github ^
    -keystore slts.p12 ^
    -storetype PKCS12 ^
    -storepass [truststore-password] ^
    -noprompt
%JAVA_HOME%\bin\keytool ^
    -import -trustcacerts ^
    -file github_api.pem ^
    -alias github_api ^
    -keystore slts.p12 ^
    -storetype PKCS12 ^
    -storepass [truststore-password] ^
    -noprompt
```
--

The last prerequisite step for GitHub is obtaining client ID and client secret for access to the GitHub developer API.

In order to obtain OAuth 2.0 credentials for GitHub,

. Log into https://github.com/[GitHub^].
. Navigate to https://github.com/settings/developers[OAuth Apps^] and click on "Register a new application".
. Enter an application name.
. Set "Homepage URL" to `\https://localhost:9443/`.
. Set "Authorization callback URL" to `\https://localhost:9443/ibm/api/social-login/redirect/githubLogin`.
. Click on "Register application".

=== Setting up for Amazon

For your application to communicate securely with GitHub using HTTPS, the TLS server public key certificates for the following domains need to be added to your application's truststore:

- `www.amazon.com` (saved as `amazon.pem`)
- `api.amazon.com` (saved as `amazon_api.pem`)

To download the certificates, run the following commands:

include::{common-includes}/os-tabs.adoc[]
[.tab_content.linux_section.mac_section]
--
[role='command']
```
keytool \
    -printcert -rfc \
    -sslserver www.amazon.com:443 \
    > amazon.pem
keytool \
    -printcert -rfc \
    -sslserver api.amazon.com:443 \
    > amazon_api.pem
```
--
[.tab_content.windows_section]
--
[role='command']
```
%JAVA_HOME%\bin\keytool ^
    -printcert -rfc ^
    -sslserver www.amazon.com:443 ^
    > amazon.pem
%JAVA_HOME%\bin\keytool ^
    -printcert -rfc ^
    -sslserver api.amazon.com:443 ^
    > amazon_api.pem
```
--

Next, run the following command to add the downloaded certificates into a keystore named `slts.p12`, which will be your application's truststore. Replace `[truststore-password]` with the password you used in the previous section for your truststore.
You will need this password in later sections in the guide.

include::{common-includes}/os-tabs.adoc[]
[.tab_content.linux_section.mac_section]
--
[role='command']
```
keytool \
    -import -trustcacerts \
    -file amazon.pem \
    -alias amazon \
    -keystore slts.p12 \
    -storetype PKCS12 \
    -storepass [truststore-password] \
    -noprompt
keytool \
    -import -trustcacerts \
    -file amazon_api.pem \
    -alias amazon_api \
    -keystore slts.p12 \
    -storetype PKCS12 \
    -storepass [truststore-password] \
    -noprompt
```
--
[.tab_content.windows_section]
--
[role='command']
```
%JAVA_HOME%\bin\keytool ^
    -import -trustcacerts ^
    -file amazon.pem ^
    -alias amazon ^
    -keystore slts.p12 ^
    -storetype PKCS12 ^
    -storepass [truststore-password] ^
    -nporompt
%JAVA_HOME%\bin\keytool ^
    -import -trustcacerts ^
    -file amazon_api.pem ^
    -alias amazon_api ^
    -keystore slts.p12 ^
    -storetype PKCS12 ^
    -storepass [truststore-password] ^
    -noprompt
```
--

The last prerequisite step for Amazon is obtaining client ID and client secret for access to the Login with Amazon API.

In order to obtain OAuth 2.0 credentials for GitHub,

. Navigate to https://login.amazon.com/[Login with Amazon^].
. Hover over "Sign-in" and click on "Developer Portal".
. Login into your Amazon account.
. Click on "Create a New Security Profile".
.. Enter a name and description.
.. Set "Consent Privacy Notice URL" to `\https://localhost.com/privacy`.
.. Click on "Save", which will return you to the "Login with Amazon Console".
. Hover over the "settings" icon under "Manage" and click on "Web Settings".
. Click on "Edit".
.. Set `\https://localhost:9443/` as the "Allowed Origins".
.. Set `\https://localhost:9443/ibm/api/social-login/redirect/amazonLogin` as the "Allowed Return URLs".
.. Click "Save".

=== Setting up for Google
For your application to communicate securely with Google using HTTPS, the TLS server public key certificates for the following domains need to be added to your application's truststore:

- `accounts.google.com` (will be saved as `google.pem`)
- `www.googleapis.com` (will be saved as `googleapis.pem`)

To download the certificates, run the following commands:

include::{common-includes}/os-tabs.adoc[]
[.tab_content.linux_section.mac_section]
--
[role='command']
```
keytool \
    -printcert -rfc \
    -sslserver accounts.google.com:443 \
    > google.pem
keytool \
    -printcert -rfc \
    -sslserver www.googleapis.com:443 \
    > googleapis.pem
```
--
[.tab_content.windows_section]
--
[role='command']
```
%JAVA_HOME%\bin\keytool ^
    -printcert -rfc ^
    -sslserver accounts.google.com:443 ^
    > google.pem
%JAVA_HOME%\bin\keytool ^
    -printcert -rfc ^
    -sslserver www.googleapis.com:443 ^
    > googleapis.pem
```
--

Next, run the following command to add the downloaded certificates into a keystore named `slts.p12`, which will be your application's truststore. Replace `[truststore-password]` with the password you used in the previous section for your truststore.
You will need this password in later sections in the guide.

include::{common-includes}/os-tabs.adoc[]
[.tab_content.linux_section.mac_section]
--
[role='command']
```
keytool \
    -import -trustcacerts \
    -file google.pem \
    -alias google \
    -keystore slts.p12 \
    -storetype PKCS12 \
    -storepass [truststore-password] \
    -noprompt
keytool \
    -import -trustcacerts \
    -file googleapis.pem \
    -alias googleapis \
    -keystore slts.p12 \
    -storetype PKCS12 \
    -storepass [truststore-password] \
    -noprompt
```

--
[.tab_content.windows_section]
--
[role='command']
```
%JAVA_HOME%\bin\keytool ^
    -import -trustcacerts ^
    -file google.pem ^
    -alias google ^
    -keystore slts.p12 ^
    -storetype PKCS12 ^
    -storepass [truststore-password] ^
    -noprompt
 %JAVA_HOME%\bin\keytool ^
    -import -trustcacerts ^
    -file googleapis.pem ^
    -alias googleapis ^
    -keystore slts.p12 ^
    -storetype PKCS12 ^
    -storepass [truststore-password] ^
    -noprompt
```
--

The last prerequisite step for Google is obtaining client ID and client secret for access to the Google developer API.

In order to obtain OAuth 2.0 credentials for Google,

. Visit the https://console.developers.google.com/[Google API Console^].
. Sign in using your Google account.
. If you haven't created a project on Google API Console before,
.. Create a new project.
.. Navigate to the "OAuth consent screen" tab.
.. Click "External", then click "Create".
.. Fill in "Application name", then click "Save".
. Navigate to the "Credentials" tab.
. Click on the "CREATE CREDENTIALS" button.
. Select "OAuth client ID" from the different options.
. Set the application type to "Web application".
. Enter the name of your OAuth 2.0 Client ID. This is different from your app name and will not be shown to end users. 
. Add `\https://localhost:9443/ibm/api/social-login/redirect/googleOIDCLogin` to "Authorized redirect URIs", then click "Create".

== Securing HelloService

First, navigate to the `start` directory.

[role='command']
include::{common-includes}/devmode-start.adoc[]

The [hotspot=helloService]`HelloService` class is the JAX-RS service that you will be securing.

[role="code_command hotspot file=0", subs="quotes"] 
----
#Replace the `HelloService` class.#
`src/main/java/io/openliberty/guides/sociallogin/HelloService.java`
----

The following new imports are required for the [hotspot=helloService]`HelloService` class:

- [hotspot=rolesAllowedImport]`javax.annotation.security.RolesAllowed`
- [hotspot=securityContextImport]`javax.ws.rs.core.SecurityContext`
- [hotspot=contextImport]`javax.ws.rs.core.Context`

The [hotspot=rolesAllowed]`@RolesAllowed({"users"})` annotation restricts access to the service to users who are
in the `users` role.

The `return "Hello, friend!";` is replaced to output user information.
The [hotspot=securityContext]`SecurityContext` context, which is injected using the
[hotspot=securityContext]`@Context` annotation, allows you to get information about the logged-in user
using [hotspot=userPrincipal]`securitContext.getUserPrincipal()`.

HelloService.java 
[source, Java, linenums, role='code_column hide_tags=copyright'] 
----
include::finish/src/main/java/io/openliberty/guides/sociallogin/HelloService.java[]
----

== Configuring the security and social media login

[role="code_command hotspot file=0", subs="quotes"] 
----
#Replace the server configuration file.#
`src/main/liberty/config/server.xml`
----

server.xml 
[source, xml, linenums, role='code_column']
----
include::finish/src/main/liberty/config/server.xml[]
----

The explanations for these changes are in the following sections.

=== Configuring the security roles

The [hotspot=applicationBnd]`<application-bnd />` configuration element under the
[hotspot=webApplication]`<webApplication />` configuration element creates a new security role [hotspot=users]`users`,
which all authenticated users belong to.
Adding this allows users that are authenticated using social media login to access your `HelloService` service.

=== Adding required features

To enable https://openliberty.io/docs/ref/feature/#socialLogin-1.0.html[Social Media Login feature^] and other required features, add new [hotspot=newFeatures]`<feature />` elements to the [hotspot=featureManager]`<featureManager />` in
`server.xml`

There are some prerequisite configurations that social media login configuration elements need:

1. The [hotspot=keystore]`<keyStore id="defaultKeyStore" .../>` configuration element
corresponds to the keystore created in the prerequisites section
2. The [hotspot=truststore]`<keyStore id="socialLoginKeyStore" .../>` configuration element corresponds to the truststore created in the prerequisites section
3. An [hotspot=sslConfig]`<ssl />` configuration element for configuring the SSL configuration that is used to connect to the social media

=== Adding keystore and truststore

In the first section, you created two keystores, `slts.p12` and `key.p12`.
Now you will configure your application to use these keystores.
Files in the `src/main/liberty` folder are copied into the location specified by `${server.output.dir}`,
so the location of these keystores is `${server.output.dir}/resources/security`.

The [hotspot=keystore]`defaultKeyStore` configuration element, whose location is `${server.output.dir}/resources/security/key.p12`,
will be used to provide SSL certificates when initiating HTTPS connections for social media login.

[role="code_command hotspot=sections", subs="quotes"] 
----
#Update the `server.xml` file.#
`src/liberty/config/server.xml`
----
[role="edit_command_text"]
Replace [hotspot=29]`[keystore-password]` with the password that you used when creating the keystore in the previous sections.

The [hotspot=truststore]`socialLoginKeyStore` configuration element, whose location is `${server.output.dir}/resources/security/slts.p12`,
will be used to store trusted certificates when initiating HTTPS connections to social media APIs for authorization and authentication.

[role="code_command hotspot=sections", subs="quotes"] 
----
#Update the `server.xml` file.#
`src/liberty/config/server.xml`
----
[role="edit_command_text"]
Replace [hotspot=22]`[truststore-password]` with the password that you used when creating the truststore in the previous sections.

The [hotspot=sslConfig]`authServiceSslRef` configuration element, which references [hotspot=keystore]`defaultKeyStore` as the keystore
and [hotspot=truststore]`socialLoginKeyStore` as the truststore, will be provided to social media login configurations.

=== Adding GitHub login configuration

[role="code_command hotspot=sections", subs="quotes"] 
----
#Update the `server.xml` file.#
`src/liberty/config/server.xml`
----
[role="edit_command_text"]
Replace the values of the [hotspot=43]`clientId` and [hotspot=44]`clientSecret` with the credentials you created for your GitHub application
in the prerequisites section.

The [hotspot=githubLogin]`<githubLogin />` configuration element will configure GitHub login.
The [hotspot=45]`sslRef` attribute is set to the [hotspot=sslConfig]`authServiceSslRef` configuration from the previous section.

=== Adding Amazon login configuration

[role="code_command hotspot=sections", subs="quotes"] 
----
#Update the `server.xml` file.#
`src/liberty/config/server.xml`
----
[role="edit_command_text"]
Replace the values of [hotspot=52]`clientId` and [hotspot=53]`clientSecret` with the credentials you created for your Amazon application
in the prerequisites section.

The [hotspot=amazonLogin]`amazonLogin` configuration uses a custom [hotspot=amazonLogin]`<oauth2Login />` configuration element.
The [hotspot=55]`sslRef` attribute is set to the [hotspot=sslConfig]`authServiceSslRef` configuration from the previous section.

Further documentation on the [hotspot=amazonLogin]`attributes` can be found on the https://openliberty.io/docs/ref/config/oauth2Login.html[Open Liberty config reference on oauth2Login^].
The values for these [hotspot=amazonLogin]`attributes` can be found in the https://developer.amazon.com/docs/login-with-amazon/minitoc-lwa-overview.html[Login With Amazon API documentation^].

Make sure that the [hotspot=50]`id` of your [hotspot=amazonLogin]`<oauth2Login />` configuration matches the redirect URL (if you set the [hotspot=50]`id` to `amazonLogin`, the redirect URL must end with `.../amazonLogin`).

=== Adding Google login configuration

[role="code_command hotspot=sections", subs="quotes"] 
----
#Update the `server.xml` file.#
`src/liberty/config/server.xml`
----
[role="edit_command_text"]
Repalce the values of [hotspot=70]`clientId` and [hotspot=71]`clientSecret` with the credentials you created for your Google application
in the prerequisites section.

The [hotspot=googleOIDCLogin]`googleOIDCLogin` configuration uses a custom [hotspot=googleOIDCLogin]`<oidcLogin />` configuration element.
The [hotspot=72]`sslRef` attribute is set to the [hotspot=sslConfig]`authServiceSslRef` configuration from the previous section.

Further documentation on the [hotspot=googleOIDCLogin]`attributes` can be found on the https://openliberty.io/docs/ref/config/oidcLogin.html[Open Liberty config reference on oidcLogin^].
The values of these [hotspot=googleOIDCLogin]`attributes` can be found in the https://developers.google.com/identity/protocols/OpenIDConnect[Google API documentation^].

Make sure that the [hotspot=68]`id` of your [hotspot=googleOIDCLogin]`<oidcLogin />` configuration matches the redirect URL (if you set the [hotspot=68]`id` to `googleOIDCLogin`, the redirect URL must end with `.../googleOIDCLogin`).

== Running the application

The Open Liberty server was started in development mode at the beginning of the guide and all the 
changes were automatically picked up.

Check out the service that you created at the
http://localhost:9080/api/hello[^] URL.

When you access https://localhost:9080/api/hello[^],
you should be redirected to a Social Media Login Form. This form allows you to choose which login provider you want to use
for authentication. When you select a login choice, you will be redirected to the login page of that service.

Try logging in using your social media accounts. After authenticating, you will be redirected back to https://localhost:9080/api/hello and the response will look like this:

[source,role="no_copy"]
---
Hello, <<your username>>
---

== Testing the service

No automated tests are provided in this guide.
You can test this service manually by starting a server and pointing a web browser at http://localhost:9080/api/hello[the endpoint for Hello service^].

== Great work! You're done!

You secured a simple RESTful web service in Open Liberty by using the Social Media Login feature.

== Related Links

Learn more about MicroProfile.

https://microprofile.io/[See the MicroProfile specs^]

https://openliberty.io/docs/ref/microprofile[View the MicroProfile API^]


include::{common-includes}/attribution.adoc[subs="attributes"]
