//  Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: social-login
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2020-06-20
:page-essential: true
:page-essential-order: 1
:page-description: Learn how to authenticate users with the Open Liberty Social Media Login feature.
:guide-author: Open Liberty
:page-tags: ['Java EE', 'Jakarta EE', 'Security']
:page-related-guides: ['microprofile-jwt']
:page-permalink: /guides/{projectid}
:page-seo-title: Authenticating users with Social Media Login
:page-seo-description: A getting started tutorial with examples on how to secure Java applications by authenticating users through social media providers, such as GitHub, using the Open Liberty Social Media Login feature.
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
= Authenticating users through social media providers

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website^].

A getting started tutorial with examples on how to secure Java applications by authenticating users through social media
providers, such as GitHub, using the Open Liberty Social Media Login feature.

== What you'll learn

Social Media Login provides a form of single sign-on (SSO) which users can use to sign in to a secured website with
their existing social media account.
It simplifies the authentication process for users and allows you to provide a secure authentication
method for your users without having to explicitly implement it.

The https://openliberty.io/docs/ref/feature/#socialLogin-1.0.html[Social Media Login Feature^] in Open Liberty
provides configuration elements to configure application authentication using one or more social media platforms,
including GitHub&reg;, LinkedIn&reg;, Facebook&reg;, Twitter&reg;, and Google&reg;.
You can also create a custom configuration for any other social media platform that implements
the https://oauth.net/2[OAuth 2.0^] or https://openid.net/connect[OpenID Connect 1.0^] standard for authorization.

By the end of this guide, you will be able to use GitHub to authenticate users to your web service.

// =================================================================================================
// Getting Started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]

== Creating a GitHub OAuth2 Application

Obtain an OAuth 2.0 client ID and client secret credentials for accessing the GitHub developer API by registering
a new application in your https://github.com/[GitHub^] account.
On the https://github.com/settings/developers[Settings > Developer settings > OAuth Apps^] page of your account,
register a new application.

Set the Homepage URL to `\https://localhost:9443` and
the authorization callback URL to `\https://localhost:9443/ibm/api/social-login/redirect/githubLogin`.

When the registration is complete, the client ID and client secret credentials are displayed.
To provide your application with the credentials, export the following environment variables: `GITHUB_CLIENT_ID` and
`GITHUB_CLIENT_SECRET`.

Replace the values of `[github-client-id]` and `[github-client-secret]` in the following command.
include::{common-includes}/os-tabs.adoc[]
[.tab_content.mac_section.linux_section]
--
[role='command']
----
export GITHUB_CLIENT_ID=[github-client-id]
export GITHUB_CLIENT_SECRET=[github-client-secret]
----
--
[.tab_content.windows_section]
--
[role='command']
----
set GITHUB_CLIENT_ID=[github-client-id]
set GITHUB_CLIENT_SECRET=[github-client-secret]
----
--

== Configuring GitHub social media login
In the `start` directory, you are provided with an application that is secured through `BASIC` authentication.
When you access the [hotspot file=1]`hello.html` page, find the [hotspot=btnLogin file=1]`login` button.

Clicking the [hotspot=btnLogin file=1]`login` button opens a login dialog that requests a username and password for
`defaultRealm`.
Enabling the Social Login feature will replace the login dialogue with social media login.

First, navigate to the `start` directory.

[role='command']
include::{common-includes}/devmode-start.adoc[]

[role="code_command", subs="quotes"]
----
#Update this `server.xml` file.#
`src/main/liberty/config/server.xml`
----
[role="edit_command_text"]
Add the [hotspot=socialLogin file=0]`socialLogin-1.0` feature definition to the existing list of features.
Add the [hotspot=githubLogin file=0]`<githubLogin />` configuration element to the server configuration.

Adding the [hotspot=socialLogin file=0]`socialLogin-1.0` feature definition enables social media login functionality to
the application, which allows you to use the [hotspot=githubLogin file=0]`<githubLogin />` configuration element to
configure GitHub login.

The client ID and client secret for your GitHub OAuth2 application are injected into the
[hotspot=githubLogin file=0]`<githubLogin />` configuration element with the values of `github.client.id` and
`github.client.secret`.
These values are supplied by the environment variables `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET`.

server.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/liberty/config/server.xml[]
----

hello.html
[source ,html, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/webapp/hello.html[]
----

HelloServlet.java
[source ,java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/sociallogin/HelloServlet.java[]
----

securedHello.jsp
[source ,html, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/webapp/securedHello.jsp[]
----

LogoutServlet.java
[source ,java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/sociallogin/LogoutServlet.java[]
----

// =================================================================================================
// Building the application
// ================================================================================================
[role='command']
include::{common-includes}/devmode-build.adoc[]

Check out the service that you created at
http://localhost:9080/api/hello.html[^].

Try logging in with your social media account.
After authentication, you are redirected to the [hotspot=login file=1]`/hello` endpoint served by
[hotspot file=2]`HelloServlet`, which serves the
[hotspot=serve file=2]`securedHello.jsp` page.

The [hotspot file=3]`securedHello.jsp` page contains a [hotspot=btnLogout file=3]`logout` button that makes a
`POST` request to the [hotspot=logout file=3]`/logout` endpoint served by [hotspot file=4]`LogoutServlet`.

Since the logout feature is not fully implemented, clicking the logout button returns an error:

[role='no_copy']
----
 Exception thrown by application class 'io.openliberty.guides.sociallogin.LogoutServlet.doPost:50'
java.lang.NullPointerException:
at io.openliberty.guides.sociallogin.LogoutServlet.doPost(LogoutServlet.java:50)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:706)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)
at [internal classes]
----

== Implementing logout

The [hotspot file=2]`LogoutServlet` provided in the `start` directory uses the
[hotspot=logout file=2]`logout()` method in the `HttpServletRequest`.
class to log the user out of the application after which the user is redirected to
[hotspot=redirect file=2]`hello.html`.

You are also provided with a [hotspot file=1]`LogoutHandler` class and [hotspot file=3]`ILogout` interface to add
custom logout logic to revoke the application's permissions from a user's account.

The [hotspot=getLogout hotspot=inject file=2]`logoutHandler.getLogout()` method gets an implementation
of `ILogout` for GitHub and uses the [hotspot=revoke file=2]`logout()` method of the `ILogout` interface to revoke
OAuth2 permissions that are granted to the application by the user.

The response returned by this [hotspot=revoke file=2]`logout()` method is verified by checking whether it has a
[hotspot=errorHandle file=2]`2xx` series status code.

The [hotspot=logout file=2]`request.logout()` method is then called to log the user out of the
application.

The [hotspot=getLogout file=2]`logoutHandler.getLogout()` method [hotspot=switch file=1]`returns` the
[hotspot=inject file=1]`implementation` of `ILogout` based on the name of the social media provider that is used
by a user. The social media provider's name is retrieved by using the
[hotspot=socialMediaName file=1]`UserProfileManager`.
The social media provider's name that is returned by [hotspot=socialMediaName file=1]`UserProfileManager` is the `id`
of the login configuration.

In this case, when the user uses GitHub, the name of the social media provider is
[hotspot=githubLoginName file=1]`githubLogin`.

Implement [hotspot file=3]`ILogout` for revoking permissions for the application from the user's GitHub account.

[role="code_command", subs="quotes"]
----
#Replace this `GitHubLogout` class.#
`src/main/java/io/openliberty/guides/sociallogin/logout/GitHubLogout.java`
----

GitHub's REST API provides a `DELETE` [hotspot=unauthorizeUrl file=0]`endpoint` that is used to revoke permissions
from the user for the application.
The JAX-RS [hotspot=delete file=0]`HttpClient` is used to send a request to this endpoint.

The [hotspot=encodeAuth file=0]`encoded` client ID and client secret, obtained from the `github.client.id` and
`github.client.secret` config properties are added to the request as an
[hotspot=authHeader file=0]`Authorization` header.

The GitHub [hotspot=accessToken file=0]`access token` that is retrieved from the user's `UserProfile` through the
[hotspot=accessToken file=0]`UserProfileManager` is sent as part of the
[hotspot=requestBody hotspot=createAccessTokenBody hotspot=addBody file=0]`request body`.


GitHubLogout.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/sociallogin/logout/GitHubLogout.java[]
----

LogoutHandler.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/sociallogin/logout/LogoutHandler.java[]
----

LogoutServlet.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/sociallogin/LogoutServlet.java[]
----

ILogout.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/sociallogin/logout/ILogout.java[]
----

// =================================================================================================
// Running the application
// ================================================================================================
The Open Liberty server was started in development mode at the beginning of the guide and all the changes were
automatically picked up.

Check out the service that you created at
http://localhost:9080/api/hello.html[^].

Try logging in with your social media account.
After authenticating, you will be redirected to `\https://localhost:9080/api/hello`.
When you click the `logout` button, you are unauthenticated and redirected back to
http://localhost:9080/api/hello.html[^].

If you try logging in again, you are asked to reauthorize your application with GitHub, and authenticated and
redirected to `\https://localhost:9080/api/hello`.

[role='command']
include::{common-includes}/devmode-quit.adoc[]

== Great work! You're done!

You secured a web application in Open Liberty by using the Social Media Login feature.

== Next steps

As an exercise, configure Facebook as a second social media provider for social media login for your application.
If more than one social media login provider is added, a selection form is presented to the user. This form contains
all the possible social media providers that are configured in your application.

Create the `<facebookLogin />` configuration element in `server.xml` to set up login for Facebook.
Similar to `<githubLogin />`, `<facebookLogin />` also requires only a client ID and client secret.

Then, implement `ILogout` as `FacebookLogout` for revoking permissions for the application from the Facebook user
account and update `LogoutHandler` to inject `FacebookLogout` and return it when the social media name is
`facebookLogin`.

The following links to Facebook documentation provides any additional information about setting up an OAuth2
application and revoking permissions.

- https://developers.facebook.com/docs/apps#register[Registering for a Facebook application^]
- https://developers.facebook.com/docs/facebook-login/web#redirecturl[Adding Facebook Login to your Facebook Application^]
- https://developers.facebook.com/docs/facebook-login/permissions/requesting-and-revoking#revokelogin[Revoking Facebook Login^]

== Related Links

Learn more about MicroProfile.

https://microprofile.io/[See the MicroProfile specs^]

https://openliberty.io/docs/ref/microprofile[View the MicroProfile API^]


include::{common-includes}/attribution.adoc[subs="attributes"]
